name: Super linter

on: [push, pull_request]

jobs:
  lint-code-base:
    name: Apply cargo fmt and cargo clippy
    # Set the agent to run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: super-linter/super-linter@v7.3.0
        env:
          VALIDATE_JSCPD: false
          VALIDATE_RUST_2015: false
          VALIDATE_RUST_2018: false
          VALIDATE_SHELL_SHFMT: false
          VALIDATE_CHECKOV: false
          VALIDATE_MARKDOWN_PRETTIER: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
